stages:
  - mirror
  - prepare
  - test
  - deploy

github_mirror:
  image: namboy94/ci-docker-environment:0.19.0
  stage: mirror
  tags: [ docker ]
  only: [ master, develop, kotlin ]
  before_script:
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
  script:
    - git-mirror-pusher git@github.com:namboy94/nuztrack.git main kotlin

compile_dotnet_script:
  image: mcr.microsoft.com/dotnet/sdk:6.0
  stage: prepare
  tags: [ docker ]
  script:
    - cd scripts/NuztrackSaves
    - dotnet publish
  artifacts:
    paths:
      - scripts/NuztrackSaves/bin
    expire_in: 1 day

test_backend:
  image: maven:3-openjdk-18
  stage: test
  tags: [ docker ]
  script:
    - mvn -B clean verify
    - cat target/site/jacoco/index.html | grep -o 'Total[^%]*%'
  coverage: '/Total.*?([0-9]{1,3})%/'

test_frontend:
  image: node:18-buster
  stage: test
  tags: [ docker ]
  script:
    - cd frontend
    - npm install
    - CI=true npm test -- --coverage
  coverage: '/All files\s*\|\s*([\d\.]+)/'

deploy_app:
  stage: deploy
  tags: [ privileged ]
  only: [ master, develop, kotlin ]
  script:
    - echo "$PROD_ENV" > .env
    - bash scripts/backup.sh backup.tar.gz
    - docker-compose build
    - docker-compose up -d
    - rm .env
  artifacts:
    paths:
      - backup.tar.gz
    expire_in: 1 month
