version: "3.2"
networks:
  net:
    driver: bridge
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: "nuztrack-backend"
    container_name: "nuztrack-backend"
    env_file: .env
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8080:8080"
    restart: always
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: "nuztrack-frontend"
    container_name: "nuztrack-frontend"
    depends_on:
      - db
      - backend
    networks:
      - net
    ports:
      - "3000:3000"
    restart: always
  db:
    image: postgres
    container_name: "nuztrack-db"
    env_file: .env
    networks:
      - net
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
  auth:
    image: "quay.io/keycloak/keycloak:18.0.0"
    container_name: "nuztrack-auth"
    command: start-dev
    env_file: .env
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: ${POSTGRES_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - db
    networks:
      - net
    ports:
      - "8081:8080"
    restart: always
volumes:
  logs: ~
  data: ~
