FROM ubuntu:22.04
MAINTAINER Hermann Krumrey <hermann@krumreyh.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y npm openjdk-18-jdk kotlin maven && npm i -g redoc-cli swagger-cli
ADD . nuztrack
RUN cd nuztrack/apidoc && bash bundle.sh && cp index.html ../src/main/resources/static/index.html
RUN cd nuztrack && mvn package && mv target/*.jar /app.jar
RUN rm -rf nuztrack

EXPOSE 8080
ENV spring_profiles_active="prod"
CMD ["/usr/bin/java", "-jar", "/app.jar"]
