FROM ubuntu:22.04
MAINTAINER Hermann Krumrey <hermann@krumreyh.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y openjdk-18-jdk kotlin maven
ADD . nuztrack
RUN cp nuztrack/apidoc/index.html nuztrack/src/main/resources/static/index.html
RUN cd nuztrack && mvn package && mv target/*.jar /app.jar
RUN rm -rf nuztrack

EXPOSE 8080
ENV spring_profiles_active="postgres"
CMD ["/usr/bin/java", "-jar", "/app.jar"]
